apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: fiap/fiap-hackathon-video-image-client
  namespace: fiap
  name: fiap-hackathon-video-image-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-hackathon-video-image-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fiap-hackathon-video-image-client
    spec:
      serviceAccountName: metrics-sa
      containers:
        - name: fiap-hackathon-video-image-client
          image: 814482976567.dkr.ecr.us-east-1.amazonaws.com/hackathon-video-image-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4080
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsNonRoot: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "512m"
          envFrom:
            - secretRef:
                name: fiap/hackathon-video-image-secrets hackathon-video-image-client-secrets
            - configMapRef:
                name: fiap-hackathon-video-image-client-vars
          readinessProbe:
              httpGet:
                  path: /v1/api/healthcheck
                  port: 4080
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
          livenessProbe:
              httpGet:
                  path: /v1/api/healthcheck
                  port: 4080
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
