apiVersion: v1
kind: Service
metadata:
  namespace: fiap
  name: $APPLICATION_NAME-svc
spec:
  type: LoadBalancer
  selector:
    app: $APPLICATION_NAME
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4080
      name: $APPLICATION_NAME-load-balancer
