apiVersion: v1
kind: Service
metadata:
  namespace: fiap
  name: fiap-hackathon-video-image-client-svc
spec:
  type: LoadBalancer
  selector:
    app: fiap-hackathon-video-image-client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4080
      name: fiap-hackathon-video-image-client-load-balancer
